# docker-compose.yaml
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: do-test-main
    tty: true
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    working_dir: /var/www
    volumes:
      - ./:/var/www

  web:
    image: nginx:stable
    container_name: do-test-web-main
    restart: always
    ports:
      - "9010:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  database:
    image: postgres:12
    container_name: do-test-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: main
    ports:
      - '37100:5432'
volumes:
  db_data:
